config/routes.rb
ShortRl::Application.routes.draw do
  resources :addresses
  match '/s/:name' => "addresses#forward_user", via: [:get, :post], :as => :forward_user

  root :to => 'addresses#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	attr_accessible :name, :location

	validates_uniqueness_of :name
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def index
		@addresses = Address.all
	end

	def forward_user
		@address = Address.find_by_name(params[:name])
		redirect_to @address.location
	end

	def new
		@address = Address.new
	end

	def create
		@address = Address.new(params[:address])
		if @address.save
			redirect_to @address
		else
			render action: "new"
		end
	end

	def show
		@address = Address.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/index.html.erb
<h2>Recently Shortened URLs</h2>
<h3>Because they're so cool</h3>

<table class="table table-striped">
<thead>
<th>Short URL</th>
<th>Long URL</th>
<th>Clicks</th>
</thead>
<tbody>
<% @addresses.each do |address| %>
<tr>
<td><a href="<%= forward_user_url(name: address.name) %>" target="_blank"><%= forward_user_url(name: address.name) %></a></td>
<td><%= address.location %></td>
<td><%= address.clicks %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/addresses/new.html.erb
<h2>Create a shorter URL</h2>

<div style="background:red; color: white; font-weight: bold;">
<% @address.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
</div>

<%= form_for @address do |form| %>
	<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
	</div>

	<div>
	<%= form.label :location, "Location - must start with http://" %>
	<%= form.text_field :location %>
	</div>
	<p><%= form.submit "Shorten it dammit!" %></p>
	<% end %>

app/views/addresses/show.html.erb
<h2>Your new short URL</h2>
<a href="<%= forward_user_url(name: @address.name) %>" alt="" target="_blank"><%= forward_user_url(name: @address.name) %></a> will direct to <%= @address.location %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortRl</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="hero-unit">
<h1>Short URL</h1>
<p>This is a site for you to create short URLs from long ones!</p>
<p><%= link_to "Get Started", new_address_url %></p>
</div>

<div class="container">
<%= yield %>
</div>
</body>
</html>